language: php

php:
  - 7.3

before_script:
  - composer self-update
  - composer install
  - composer dump-autoload -o

script: vendor/bin/phpunit --verbose

notifications:
  email:
    - dave@aphiria.com

sudo: false

matrix:
  fast_finish: true