networks:
  aphiria:

services:
  app:
    build:
      context: ./infrastructure/docker
      dockerfile: nginx.dockerfile
    volumes:
      - ./:/usr/share/nginx/html
      - ./infrastructure/docker/nginx.conf:/etc/nginx/conf.d/default.conf
    command: >
      sh -c "chmod -R 777 /usr/share/nginx/html/tmp && nginx -g 'daemon off;'"
    depends_on:
      - php
    ports:
      - "8080:80"
    networks:
      - aphiria

  php:
    build:
      context: ./infrastructure/docker
      dockerfile: php.dockerfile
    volumes:
      - ./:/usr/share/nginx/html
    ports:
      - "9003:9003"
    networks:
      - aphiria

  aphiria:
    build:
      context: ./infrastructure/docker
      dockerfile: php.dockerfile
    volumes:
      - ./:/usr/share/nginx/html
    entrypoint: [ 'php', '/usr/share/nginx/html/aphiria' ]
    networks:
      - aphiria
