name: ci
on:
  push:
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: ['8.0']
        stability: [prefer-stable]
    name: PHP ${{ matrix.php }} - ${{ matrix.stability }}
    steps:
      - name: Check Out Code
        uses: actions/checkout@v2
      - name: Set Up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, dom, libxml, mbstring, pcntl, zip
          tools: composer:v2
      - name: Install Dependencies
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress
      - name: Run Tests
        run: vendor/bin/phpunit --verbose
      #- name: Run Linter
      #  run: composer run-script lint-check
