name: ci
on:
  push:
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - php: '8.1'
            stability: prefer-stable
            experimental: false
            php-cs-fixer-ignore-php-version: 1
    name: PHP ${{ matrix.php }} - ${{ matrix.stability }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - name: Check Out Code
        uses: actions/checkout@v2
      - name: Set Up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, dom, libxml, mbstring, pcntl, zip
          tools: composer:v2
      - name: Install Dependencies
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress
      - name: Run Tests
        run: composer phpunit
      # For now, do not run the linter until PHP-CS-Fixer fully supports this PHP version
      - name: Run Linter
        if: matrix.php-cs-fixer-ignore-php-version == 0
        run: composer phpcs-test
        env:
          PHP_CS_FIXER_IGNORE_ENV: ${{ matrix.php-cs-fixer-ignore-php-version }}
      - name: Run Psalm Static Analysis
        run: composer psalm
